### PR TITLE
chore: fix `npm run autod`

### PR DESCRIPTION
**Pull request by nightink**

### CODE REVIEW

**Comment by hemanth** [comment]
Build is failing after [77921863](https://travis-ci.org/node-modules/cfork/builds/77921863)

**Comment by nightink** [comment]
@hemanth  can you retry?

**Comment by hemanth** [comment]
@nightink [L274](https://travis-ci.org/node-modules/cfork/jobs/81239632#L274)

**Comment by nightink** [comment]
ping @fengmk2 
local test pass. :cry:

**Pull request merged**
